//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaElectronica.WSPrint.Reportes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReporteBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReporteBase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacturaElectronica.WSPrint.Reportes.ReporteBase", typeof(ReporteBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomMargin.
        /// </summary>
        public static string BottomMargin_Name {
            get {
                return ResourceManager.GetString("BottomMargin.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CbteDetails.
        /// </summary>
        public static string CbteDetails_Name {
            get {
                return ResourceManager.GetString("CbteDetails.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controlStyle1.
        /// </summary>
        public static string controlStyle1_Name {
            get {
                return ResourceManager.GetString("controlStyle1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail_Name {
            get {
                return ResourceManager.GetString("Detail.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formattingRule1.
        /// </summary>
        public static string formattingRule1_Name {
            get {
                return ResourceManager.GetString("formattingRule1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupFooter0.
        /// </summary>
        public static string GroupFooter0_Name {
            get {
                return ResourceManager.GetString("GroupFooter0.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupFooter1.
        /// </summary>
        public static string GroupFooter1_Name {
            get {
                return ResourceManager.GetString("GroupFooter1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupFooter2.
        /// </summary>
        public static string GroupFooter2_Name {
            get {
                return ResourceManager.GetString("GroupFooter2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupFooter3.
        /// </summary>
        public static string GroupFooter3_Name {
            get {
                return ResourceManager.GetString("GroupFooter3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupFooter4.
        /// </summary>
        public static string GroupFooter4_Name {
            get {
                return ResourceManager.GetString("GroupFooter4.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupFooter5.
        /// </summary>
        public static string GroupFooter5_Name {
            get {
                return ResourceManager.GetString("GroupFooter5.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupHeader1.
        /// </summary>
        public static string GroupHeader1_Name {
            get {
                return ResourceManager.GetString("GroupHeader1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl1.
        /// </summary>
        public static string lbl1_Name {
            get {
                return ResourceManager.GetString("lbl1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl10.
        /// </summary>
        public static string lbl10_Name {
            get {
                return ResourceManager.GetString("lbl10.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl11.
        /// </summary>
        public static string lbl11_Name {
            get {
                return ResourceManager.GetString("lbl11.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl15.
        /// </summary>
        public static string lbl15_Name {
            get {
                return ResourceManager.GetString("lbl15.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl16.
        /// </summary>
        public static string lbl16_Name {
            get {
                return ResourceManager.GetString("lbl16.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl17.
        /// </summary>
        public static string lbl17_Name {
            get {
                return ResourceManager.GetString("lbl17.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl18.
        /// </summary>
        public static string lbl18_Name {
            get {
                return ResourceManager.GetString("lbl18.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl19.
        /// </summary>
        public static string lbl19_Name {
            get {
                return ResourceManager.GetString("lbl19.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl2.
        /// </summary>
        public static string lbl2_Name {
            get {
                return ResourceManager.GetString("lbl2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl20.
        /// </summary>
        public static string lbl20_Name {
            get {
                return ResourceManager.GetString("lbl20.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl3.
        /// </summary>
        public static string lbl3_Name {
            get {
                return ResourceManager.GetString("lbl3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl4.
        /// </summary>
        public static string lbl4_Name {
            get {
                return ResourceManager.GetString("lbl4.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl5.
        /// </summary>
        public static string lbl5_Name {
            get {
                return ResourceManager.GetString("lbl5.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl6.
        /// </summary>
        public static string lbl6_Name {
            get {
                return ResourceManager.GetString("lbl6.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl7.
        /// </summary>
        public static string lbl7_Name {
            get {
                return ResourceManager.GetString("lbl7.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblTituloPercepcionIIBBDocsB.
        /// </summary>
        public static string lblTituloPercepcionIIBBDocsB_Name {
            get {
                return ResourceManager.GetString("lblTituloPercepcionIIBBDocsB.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblTituloRapipago.
        /// </summary>
        public static string lblTituloRapipago_Name {
            get {
                return ResourceManager.GetString("lblTituloRapipago.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageFooter.
        /// </summary>
        public static string PageFooter_Name {
            get {
                return ResourceManager.GetString("PageFooter.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageHeader.
        /// </summary>
        public static string PageHeader_Name {
            get {
                return ResourceManager.GetString("PageHeader.Name", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap picLogoCabecera_Image {
            get {
                object obj = ResourceManager.GetObject("picLogoCabecera.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picLogoCabecera.
        /// </summary>
        public static string picLogoCabecera_Name {
            get {
                return ResourceManager.GetString("picLogoCabecera.Name", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap picLogoRapipago_Image {
            get {
                object obj = ResourceManager.GetObject("picLogoRapipago.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picLogoRapipago.
        /// </summary>
        public static string picLogoRapipago_Name {
            get {
                return ResourceManager.GetString("picLogoRapipago.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtbDatosEmpresa.
        /// </summary>
        public static string rtbDatosEmpresa_Name {
            get {
                return ResourceManager.GetString("rtbDatosEmpresa.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ewBcAHIAdABmADEAXABhAG4AcwBpAFwAYQBuAHMAaQBjAHAAZwAxADIANQAyAFwAZABlAGYAZgAwAHsAXABmAG8AbgB0AHQAYgBsAHsAXABmADAAXABmAG4AaQBsAFwAZgBjAGgAYQByAHMAZQB0ADAAIABBAHIAaQBhAGwAOwB9AHsAXABmADEAXABmAG4AaQBsACAAQQByAGkAYQBsADsAfQB9AA0ACgB7AFwAYwBvAGwAbwByAHQAYgBsACAAOwBcAHIAZQBkADAAXABnAHIAZQBlAG4AMABcAGIAbAB1AGUAMAA7AH0ADQAKAFwAdgBpAGUAdwBrAGkAbgBkADQAXAB1AGMAMQBcAHAAYQByAGQAXABxAHIAXABjAGYAMQBcAGwAYQBuAGcAMQAxADIANwA0AFwAYgBcAGkAXABmAHMAMQA4ACAARgB1AG4AZABhAGMAaQBcACcAZgAzAG4AIABGAGEAdgBhAGwAbwByAG8AXABjAGYAMABcAHAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rtbDatosEmpresa_SerializableRtfString {
            get {
                return ResourceManager.GetString("rtbDatosEmpresa.SerializableRtfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtbDatosEmpresa2.
        /// </summary>
        public static string rtbDatosEmpresa2_Name {
            get {
                return ResourceManager.GetString("rtbDatosEmpresa2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ewBcAHIAdABmADEAXABhAG4AcwBpAGMAcABnADEAMgA1ADIADQAKAHsADQAKAFwAZgBvAG4AdAB0AGIAbAANAAoAewBcAGYAMAAgAFQAaQBtAGUAcwAgAE4AZQB3ACAAUgBvAG0AYQBuADsAfQANAAoAewBcAGYAMQAgAEEAcgBpAGEAbAA7AH0ADQAKAH0ADQAKAHsADQAKAFwAYwBvAGwAbwByAHQAYgBsAA0ACgA7AA0ACgBcAHIAZQBkADAAXABnAHIAZQBlAG4AMABcAGIAbAB1AGUAMAA7AA0ACgBcAHIAZQBkADAAXABnAHIAZQBlAG4AMABcAGIAbAB1AGUAMgA1ADUAOwANAAoAfQANAAoAewBcAHMAZQBjAHQAZABcAHAAYQByAGQAXABwAGwAYQBpAG4AXABxAGwAewBcAGYAMQBcAGYAcwAxADgAXABjAGYAMQAgAEMALgBVAC4ASQAuAFQALgAgAE4AXAB1ADEANwA2AFwAJwBiADAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rtbDatosEmpresa2_SerializableRtfString {
            get {
                return ResourceManager.GetString("rtbDatosEmpresa2.SerializableRtfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtbDatosEmpresa3.
        /// </summary>
        public static string rtbDatosEmpresa3_Name {
            get {
                return ResourceManager.GetString("rtbDatosEmpresa3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ewBcAHIAdABmADEAXABhAG4AcwBpAGMAcABnADEAMgA1ADIADQAKAHsADQAKAFwAZgBvAG4AdAB0AGIAbAANAAoAewBcAGYAMAAgAFQAaQBtAGUAcwAgAE4AZQB3ACAAUgBvAG0AYQBuADsAfQANAAoAewBcAGYAMQAgAEEAcgBpAGEAbAA7AH0ADQAKAH0ADQAKAHsADQAKAFwAYwBvAGwAbwByAHQAYgBsAA0ACgA7AA0ACgBcAHIAZQBkADAAXABnAHIAZQBlAG4AMABcAGIAbAB1AGUAMAA7AA0ACgBcAHIAZQBkADAAXABnAHIAZQBlAG4AMABcAGIAbAB1AGUAMgA1ADUAOwANAAoAfQANAAoAewBcAHMAZQBjAHQAZABcAHAAYQByAGQAXABwAGwAYQBpAG4AXABxAGwAewBcAGYAMQBcAGYAcwAxADgAXABjAGYAMQAgADMAMwAtADUANQA5ADcANgA4ADgANgAtADkAfQBcAGYAMQBcAGYA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rtbDatosEmpresa3_SerializableRtfString {
            get {
                return ResourceManager.GetString("rtbDatosEmpresa3.SerializableRtfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopMargin.
        /// </summary>
        public static string TopMargin_Name {
            get {
                return ResourceManager.GetString("TopMargin.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txCPer.
        /// </summary>
        public static string txCPer_Name {
            get {
                return ResourceManager.GetString("txCPer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtBarCodeCbte.
        /// </summary>
        public static string txtBarCodeCbte_Name {
            get {
                return ResourceManager.GetString("txtBarCodeCbte.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtBarCodeRapipago.
        /// </summary>
        public static string txtBarCodeRapipago_Name {
            get {
                return ResourceManager.GetString("txtBarCodeRapipago.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtBarcodeRapipago2.
        /// </summary>
        public static string txtBarcodeRapipago2_Name {
            get {
                return ResourceManager.GetString("txtBarcodeRapipago2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtCae.
        /// </summary>
        public static string txtCae_Name {
            get {
                return ResourceManager.GetString("txtCae.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtCodeRapipago.
        /// </summary>
        public static string txtCodeRapipago_Name {
            get {
                return ResourceManager.GetString("txtCodeRapipago.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtCondiciondeVenta.
        /// </summary>
        public static string txtCondiciondeVenta_Name {
            get {
                return ResourceManager.GetString("txtCondiciondeVenta.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtDAGRUF.
        /// </summary>
        public static string txtDAGRUF_Name {
            get {
                return ResourceManager.GetString("txtDAGRUF.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtDomicilio.
        /// </summary>
        public static string txtDomicilio_Name {
            get {
                return ResourceManager.GetString("txtDomicilio.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtFechaCbte.
        /// </summary>
        public static string txtFechaCbte_Name {
            get {
                return ResourceManager.GetString("txtFechaCbte.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtFechaVto.
        /// </summary>
        public static string txtFechaVto_Name {
            get {
                return ResourceManager.GetString("txtFechaVto.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtImporteIIBBMonedaFacturacion.
        /// </summary>
        public static string txtImporteIIBBMonedaFacturacion_Name {
            get {
                return ResourceManager.GetString("txtImporteIIBBMonedaFacturacion.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtInformacionAdicional.
        /// </summary>
        public static string txtInformacionAdicional_Name {
            get {
                return ResourceManager.GetString("txtInformacionAdicional.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtLetraCbte.
        /// </summary>
        public static string txtLetraCbte_Name {
            get {
                return ResourceManager.GetString("txtLetraCbte.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtLugarDeEntrega.
        /// </summary>
        public static string txtLugarDeEntrega_Name {
            get {
                return ResourceManager.GetString("txtLugarDeEntrega.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtMoneda.
        /// </summary>
        public static string txtMoneda_Name {
            get {
                return ResourceManager.GetString("txtMoneda.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtNombreEmpresa.
        /// </summary>
        public static string txtNombreEmpresa_Name {
            get {
                return ResourceManager.GetString("txtNombreEmpresa.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtNroCbte.
        /// </summary>
        public static string txtNroCbte_Name {
            get {
                return ResourceManager.GetString("txtNroCbte.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtNumCodigo.
        /// </summary>
        public static string txtNumCodigo_Name {
            get {
                return ResourceManager.GetString("txtNumCodigo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtNumCodIIBB.
        /// </summary>
        public static string txtNumCodIIBB_Name {
            get {
                return ResourceManager.GetString("txtNumCodIIBB.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtNumCuit.
        /// </summary>
        public static string txtNumCuit_Name {
            get {
                return ResourceManager.GetString("txtNumCuit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtNumIIBB.
        /// </summary>
        public static string txtNumIIBB_Name {
            get {
                return ResourceManager.GetString("txtNumIIBB.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtObservaciones3.
        /// </summary>
        public static string txtObservaciones3_Name {
            get {
                return ResourceManager.GetString("txtObservaciones3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtPercepcionIIBBDocsB.
        /// </summary>
        public static string txtPercepcionIIBBDocsB_Name {
            get {
                return ResourceManager.GetString("txtPercepcionIIBBDocsB.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtRefInterna.
        /// </summary>
        public static string txtRefInterna_Name {
            get {
                return ResourceManager.GetString("txtRefInterna.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtSon.
        /// </summary>
        public static string txtSon_Name {
            get {
                return ResourceManager.GetString("txtSon.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtTipo.
        /// </summary>
        public static string txtTipo_Name {
            get {
                return ResourceManager.GetString("txtTipo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtTipoCbte.
        /// </summary>
        public static string txtTipoCbte_Name {
            get {
                return ResourceManager.GetString("txtTipoCbte.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtTipoIva.
        /// </summary>
        public static string txtTipoIva_Name {
            get {
                return ResourceManager.GetString("txtTipoIva.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtTotal.
        /// </summary>
        public static string txtTotal_Name {
            get {
                return ResourceManager.GetString("txtTotal.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtUsuario.
        /// </summary>
        public static string txtUsuario_Name {
            get {
                return ResourceManager.GetString("txtUsuario.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrCrossBandBox1.
        /// </summary>
        public static string xrCrossBandBox1_Name {
            get {
                return ResourceManager.GetString("xrCrossBandBox1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLabel2.
        /// </summary>
        public static string xrLabel2_Name {
            get {
                return ResourceManager.GetString("xrLabel2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLabel3.
        /// </summary>
        public static string xrLabel3_Name {
            get {
                return ResourceManager.GetString("xrLabel3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLine1.
        /// </summary>
        public static string xrLine1_Name {
            get {
                return ResourceManager.GetString("xrLine1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLine2.
        /// </summary>
        public static string xrLine2_Name {
            get {
                return ResourceManager.GetString("xrLine2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLine3.
        /// </summary>
        public static string xrLine3_Name {
            get {
                return ResourceManager.GetString("xrLine3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLine4.
        /// </summary>
        public static string xrLine4_Name {
            get {
                return ResourceManager.GetString("xrLine4.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLine5.
        /// </summary>
        public static string xrLine5_Name {
            get {
                return ResourceManager.GetString("xrLine5.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLine6.
        /// </summary>
        public static string xrLine6_Name {
            get {
                return ResourceManager.GetString("xrLine6.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrLine7.
        /// </summary>
        public static string xrLine7_Name {
            get {
                return ResourceManager.GetString("xrLine7.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrPageInfo1.
        /// </summary>
        public static string xrPageInfo1_Name {
            get {
                return ResourceManager.GetString("xrPageInfo1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrPanel1.
        /// </summary>
        public static string xrPanel1_Name {
            get {
                return ResourceManager.GetString("xrPanel1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTable2.
        /// </summary>
        public static string xrTable2_Name {
            get {
                return ResourceManager.GetString("xrTable2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableCell1.
        /// </summary>
        public static string xrTableCell1_Name {
            get {
                return ResourceManager.GetString("xrTableCell1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableCell2.
        /// </summary>
        public static string xrTableCell2_Name {
            get {
                return ResourceManager.GetString("xrTableCell2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableCellDetalle.
        /// </summary>
        public static string xrTableCellDetalle_Name {
            get {
                return ResourceManager.GetString("xrTableCellDetalle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableCellLabelDetalle.
        /// </summary>
        public static string xrTableCellLabelDetalle_Name {
            get {
                return ResourceManager.GetString("xrTableCellLabelDetalle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableCellLabelTotal.
        /// </summary>
        public static string xrTableCellLabelTotal_Name {
            get {
                return ResourceManager.GetString("xrTableCellLabelTotal.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableCellTotal.
        /// </summary>
        public static string xrTableCellTotal_Name {
            get {
                return ResourceManager.GetString("xrTableCellTotal.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableImportes.
        /// </summary>
        public static string xrTableImportes_Name {
            get {
                return ResourceManager.GetString("xrTableImportes.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableRow1.
        /// </summary>
        public static string xrTableRow1_Name {
            get {
                return ResourceManager.GetString("xrTableRow1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableRow2.
        /// </summary>
        public static string xrTableRow2_Name {
            get {
                return ResourceManager.GetString("xrTableRow2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrTableRow3.
        /// </summary>
        public static string xrTableRow3_Name {
            get {
                return ResourceManager.GetString("xrTableRow3.Name", resourceCulture);
            }
        }
    }
}
