//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace FacturaElectronica.WebServices.wsbfe {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BFEAuthorizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetCMPOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetPARAM_Tipo_docOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetPARAM_Tipo_IVAOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetPARAM_ZonasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetPARAM_Tipo_CbteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetPARAM_UMedOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetPARAM_NCMOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetPARAM_MONOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetLast_CMPOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEDummyOperationCompleted;
        
        private System.Threading.SendOrPostCallback BFEGetLast_IDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::FacturaElectronica.WebServices.Properties.Settings.Default.FacturaElectronica_WebServices_wsbfe_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BFEAuthorizeCompletedEventHandler BFEAuthorizeCompleted;
        
        /// <remarks/>
        public event BFEGetCMPCompletedEventHandler BFEGetCMPCompleted;
        
        /// <remarks/>
        public event BFEGetPARAM_Tipo_docCompletedEventHandler BFEGetPARAM_Tipo_docCompleted;
        
        /// <remarks/>
        public event BFEGetPARAM_Tipo_IVACompletedEventHandler BFEGetPARAM_Tipo_IVACompleted;
        
        /// <remarks/>
        public event BFEGetPARAM_ZonasCompletedEventHandler BFEGetPARAM_ZonasCompleted;
        
        /// <remarks/>
        public event BFEGetPARAM_Tipo_CbteCompletedEventHandler BFEGetPARAM_Tipo_CbteCompleted;
        
        /// <remarks/>
        public event BFEGetPARAM_UMedCompletedEventHandler BFEGetPARAM_UMedCompleted;
        
        /// <remarks/>
        public event BFEGetPARAM_NCMCompletedEventHandler BFEGetPARAM_NCMCompleted;
        
        /// <remarks/>
        public event BFEGetPARAM_MONCompletedEventHandler BFEGetPARAM_MONCompleted;
        
        /// <remarks/>
        public event BFEGetLast_CMPCompletedEventHandler BFEGetLast_CMPCompleted;
        
        /// <remarks/>
        public event BFEDummyCompletedEventHandler BFEDummyCompleted;
        
        /// <remarks/>
        public event BFEGetLast_IDCompletedEventHandler BFEGetLast_IDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEAuthorize", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponseAuthorize BFEAuthorize(ClsBFEAuthRequest Auth, ClsBFERequest Cmp) {
            object[] results = this.Invoke("BFEAuthorize", new object[] {
                        Auth,
                        Cmp});
            return ((BFEResponseAuthorize)(results[0]));
        }
        
        /// <remarks/>
        public void BFEAuthorizeAsync(ClsBFEAuthRequest Auth, ClsBFERequest Cmp) {
            this.BFEAuthorizeAsync(Auth, Cmp, null);
        }
        
        /// <remarks/>
        public void BFEAuthorizeAsync(ClsBFEAuthRequest Auth, ClsBFERequest Cmp, object userState) {
            if ((this.BFEAuthorizeOperationCompleted == null)) {
                this.BFEAuthorizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEAuthorizeOperationCompleted);
            }
            this.InvokeAsync("BFEAuthorize", new object[] {
                        Auth,
                        Cmp}, this.BFEAuthorizeOperationCompleted, userState);
        }
        
        private void OnBFEAuthorizeOperationCompleted(object arg) {
            if ((this.BFEAuthorizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEAuthorizeCompleted(this, new BFEAuthorizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetCMP", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEGetCMPResponse BFEGetCMP(ClsBFEAuthRequest Auth, ClsBFEGetCMP Cmp) {
            object[] results = this.Invoke("BFEGetCMP", new object[] {
                        Auth,
                        Cmp});
            return ((BFEGetCMPResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetCMPAsync(ClsBFEAuthRequest Auth, ClsBFEGetCMP Cmp) {
            this.BFEGetCMPAsync(Auth, Cmp, null);
        }
        
        /// <remarks/>
        public void BFEGetCMPAsync(ClsBFEAuthRequest Auth, ClsBFEGetCMP Cmp, object userState) {
            if ((this.BFEGetCMPOperationCompleted == null)) {
                this.BFEGetCMPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetCMPOperationCompleted);
            }
            this.InvokeAsync("BFEGetCMP", new object[] {
                        Auth,
                        Cmp}, this.BFEGetCMPOperationCompleted, userState);
        }
        
        private void OnBFEGetCMPOperationCompleted(object arg) {
            if ((this.BFEGetCMPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetCMPCompleted(this, new BFEGetCMPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Tipo_doc", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_Tipo_doc BFEGetPARAM_Tipo_doc(ClsBFEAuthRequest auth) {
            object[] results = this.Invoke("BFEGetPARAM_Tipo_doc", new object[] {
                        auth});
            return ((BFEResponse_Tipo_doc)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetPARAM_Tipo_docAsync(ClsBFEAuthRequest auth) {
            this.BFEGetPARAM_Tipo_docAsync(auth, null);
        }
        
        /// <remarks/>
        public void BFEGetPARAM_Tipo_docAsync(ClsBFEAuthRequest auth, object userState) {
            if ((this.BFEGetPARAM_Tipo_docOperationCompleted == null)) {
                this.BFEGetPARAM_Tipo_docOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetPARAM_Tipo_docOperationCompleted);
            }
            this.InvokeAsync("BFEGetPARAM_Tipo_doc", new object[] {
                        auth}, this.BFEGetPARAM_Tipo_docOperationCompleted, userState);
        }
        
        private void OnBFEGetPARAM_Tipo_docOperationCompleted(object arg) {
            if ((this.BFEGetPARAM_Tipo_docCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetPARAM_Tipo_docCompleted(this, new BFEGetPARAM_Tipo_docCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Tipo_IVA", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_Tipo_IVA BFEGetPARAM_Tipo_IVA(ClsBFEAuthRequest auth) {
            object[] results = this.Invoke("BFEGetPARAM_Tipo_IVA", new object[] {
                        auth});
            return ((BFEResponse_Tipo_IVA)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetPARAM_Tipo_IVAAsync(ClsBFEAuthRequest auth) {
            this.BFEGetPARAM_Tipo_IVAAsync(auth, null);
        }
        
        /// <remarks/>
        public void BFEGetPARAM_Tipo_IVAAsync(ClsBFEAuthRequest auth, object userState) {
            if ((this.BFEGetPARAM_Tipo_IVAOperationCompleted == null)) {
                this.BFEGetPARAM_Tipo_IVAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetPARAM_Tipo_IVAOperationCompleted);
            }
            this.InvokeAsync("BFEGetPARAM_Tipo_IVA", new object[] {
                        auth}, this.BFEGetPARAM_Tipo_IVAOperationCompleted, userState);
        }
        
        private void OnBFEGetPARAM_Tipo_IVAOperationCompleted(object arg) {
            if ((this.BFEGetPARAM_Tipo_IVACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetPARAM_Tipo_IVACompleted(this, new BFEGetPARAM_Tipo_IVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Zonas", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_Zon BFEGetPARAM_Zonas(ClsBFEAuthRequest auth) {
            object[] results = this.Invoke("BFEGetPARAM_Zonas", new object[] {
                        auth});
            return ((BFEResponse_Zon)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetPARAM_ZonasAsync(ClsBFEAuthRequest auth) {
            this.BFEGetPARAM_ZonasAsync(auth, null);
        }
        
        /// <remarks/>
        public void BFEGetPARAM_ZonasAsync(ClsBFEAuthRequest auth, object userState) {
            if ((this.BFEGetPARAM_ZonasOperationCompleted == null)) {
                this.BFEGetPARAM_ZonasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetPARAM_ZonasOperationCompleted);
            }
            this.InvokeAsync("BFEGetPARAM_Zonas", new object[] {
                        auth}, this.BFEGetPARAM_ZonasOperationCompleted, userState);
        }
        
        private void OnBFEGetPARAM_ZonasOperationCompleted(object arg) {
            if ((this.BFEGetPARAM_ZonasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetPARAM_ZonasCompleted(this, new BFEGetPARAM_ZonasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_Tipo_Cbte", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_Tipo_Cbte BFEGetPARAM_Tipo_Cbte(ClsBFEAuthRequest auth) {
            object[] results = this.Invoke("BFEGetPARAM_Tipo_Cbte", new object[] {
                        auth});
            return ((BFEResponse_Tipo_Cbte)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetPARAM_Tipo_CbteAsync(ClsBFEAuthRequest auth) {
            this.BFEGetPARAM_Tipo_CbteAsync(auth, null);
        }
        
        /// <remarks/>
        public void BFEGetPARAM_Tipo_CbteAsync(ClsBFEAuthRequest auth, object userState) {
            if ((this.BFEGetPARAM_Tipo_CbteOperationCompleted == null)) {
                this.BFEGetPARAM_Tipo_CbteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetPARAM_Tipo_CbteOperationCompleted);
            }
            this.InvokeAsync("BFEGetPARAM_Tipo_Cbte", new object[] {
                        auth}, this.BFEGetPARAM_Tipo_CbteOperationCompleted, userState);
        }
        
        private void OnBFEGetPARAM_Tipo_CbteOperationCompleted(object arg) {
            if ((this.BFEGetPARAM_Tipo_CbteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetPARAM_Tipo_CbteCompleted(this, new BFEGetPARAM_Tipo_CbteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_UMed", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_Umed BFEGetPARAM_UMed(ClsBFEAuthRequest auth) {
            object[] results = this.Invoke("BFEGetPARAM_UMed", new object[] {
                        auth});
            return ((BFEResponse_Umed)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetPARAM_UMedAsync(ClsBFEAuthRequest auth) {
            this.BFEGetPARAM_UMedAsync(auth, null);
        }
        
        /// <remarks/>
        public void BFEGetPARAM_UMedAsync(ClsBFEAuthRequest auth, object userState) {
            if ((this.BFEGetPARAM_UMedOperationCompleted == null)) {
                this.BFEGetPARAM_UMedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetPARAM_UMedOperationCompleted);
            }
            this.InvokeAsync("BFEGetPARAM_UMed", new object[] {
                        auth}, this.BFEGetPARAM_UMedOperationCompleted, userState);
        }
        
        private void OnBFEGetPARAM_UMedOperationCompleted(object arg) {
            if ((this.BFEGetPARAM_UMedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetPARAM_UMedCompleted(this, new BFEGetPARAM_UMedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_NCM", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_NCM BFEGetPARAM_NCM(ClsBFEAuthRequest Auth) {
            object[] results = this.Invoke("BFEGetPARAM_NCM", new object[] {
                        Auth});
            return ((BFEResponse_NCM)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetPARAM_NCMAsync(ClsBFEAuthRequest Auth) {
            this.BFEGetPARAM_NCMAsync(Auth, null);
        }
        
        /// <remarks/>
        public void BFEGetPARAM_NCMAsync(ClsBFEAuthRequest Auth, object userState) {
            if ((this.BFEGetPARAM_NCMOperationCompleted == null)) {
                this.BFEGetPARAM_NCMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetPARAM_NCMOperationCompleted);
            }
            this.InvokeAsync("BFEGetPARAM_NCM", new object[] {
                        Auth}, this.BFEGetPARAM_NCMOperationCompleted, userState);
        }
        
        private void OnBFEGetPARAM_NCMOperationCompleted(object arg) {
            if ((this.BFEGetPARAM_NCMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetPARAM_NCMCompleted(this, new BFEGetPARAM_NCMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetPARAM_MON", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_Mon BFEGetPARAM_MON(ClsBFEAuthRequest auth) {
            object[] results = this.Invoke("BFEGetPARAM_MON", new object[] {
                        auth});
            return ((BFEResponse_Mon)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetPARAM_MONAsync(ClsBFEAuthRequest auth) {
            this.BFEGetPARAM_MONAsync(auth, null);
        }
        
        /// <remarks/>
        public void BFEGetPARAM_MONAsync(ClsBFEAuthRequest auth, object userState) {
            if ((this.BFEGetPARAM_MONOperationCompleted == null)) {
                this.BFEGetPARAM_MONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetPARAM_MONOperationCompleted);
            }
            this.InvokeAsync("BFEGetPARAM_MON", new object[] {
                        auth}, this.BFEGetPARAM_MONOperationCompleted, userState);
        }
        
        private void OnBFEGetPARAM_MONOperationCompleted(object arg) {
            if ((this.BFEGetPARAM_MONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetPARAM_MONCompleted(this, new BFEGetPARAM_MONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetLast_CMP", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponseLast_CMP BFEGetLast_CMP(ClsBFE_LastCMP Auth) {
            object[] results = this.Invoke("BFEGetLast_CMP", new object[] {
                        Auth});
            return ((BFEResponseLast_CMP)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetLast_CMPAsync(ClsBFE_LastCMP Auth) {
            this.BFEGetLast_CMPAsync(Auth, null);
        }
        
        /// <remarks/>
        public void BFEGetLast_CMPAsync(ClsBFE_LastCMP Auth, object userState) {
            if ((this.BFEGetLast_CMPOperationCompleted == null)) {
                this.BFEGetLast_CMPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetLast_CMPOperationCompleted);
            }
            this.InvokeAsync("BFEGetLast_CMP", new object[] {
                        Auth}, this.BFEGetLast_CMPOperationCompleted, userState);
        }
        
        private void OnBFEGetLast_CMPOperationCompleted(object arg) {
            if ((this.BFEGetLast_CMPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetLast_CMPCompleted(this, new BFEGetLast_CMPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEDummy", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DummyResponse BFEDummy() {
            object[] results = this.Invoke("BFEDummy", new object[0]);
            return ((DummyResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BFEDummyAsync() {
            this.BFEDummyAsync(null);
        }
        
        /// <remarks/>
        public void BFEDummyAsync(object userState) {
            if ((this.BFEDummyOperationCompleted == null)) {
                this.BFEDummyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEDummyOperationCompleted);
            }
            this.InvokeAsync("BFEDummy", new object[0], this.BFEDummyOperationCompleted, userState);
        }
        
        private void OnBFEDummyOperationCompleted(object arg) {
            if ((this.BFEDummyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEDummyCompleted(this, new BFEDummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.bfe/BFEGetLast_ID", RequestNamespace="http://ar.gov.afip.dif.bfe/", ResponseNamespace="http://ar.gov.afip.dif.bfe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BFEResponse_LastID BFEGetLast_ID(ClsBFEAuthRequest Auth) {
            object[] results = this.Invoke("BFEGetLast_ID", new object[] {
                        Auth});
            return ((BFEResponse_LastID)(results[0]));
        }
        
        /// <remarks/>
        public void BFEGetLast_IDAsync(ClsBFEAuthRequest Auth) {
            this.BFEGetLast_IDAsync(Auth, null);
        }
        
        /// <remarks/>
        public void BFEGetLast_IDAsync(ClsBFEAuthRequest Auth, object userState) {
            if ((this.BFEGetLast_IDOperationCompleted == null)) {
                this.BFEGetLast_IDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBFEGetLast_IDOperationCompleted);
            }
            this.InvokeAsync("BFEGetLast_ID", new object[] {
                        Auth}, this.BFEGetLast_IDOperationCompleted, userState);
        }
        
        private void OnBFEGetLast_IDOperationCompleted(object arg) {
            if ((this.BFEGetLast_IDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BFEGetLast_IDCompleted(this, new BFEGetLast_IDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEAuthRequest {
        
        private string tokenField;
        
        private string signField;
        
        private long cuitField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        public long Cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_LastID {
        
        private long idField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_LastID {
        
        private ClsBFEResponse_LastID bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_LastID BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEErr {
        
        private int errCodeField;
        
        private string errMsgField;
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEEvents {
        
        private int eventCodeField;
        
        private string eventMsgField;
        
        /// <remarks/>
        public int EventCode {
            get {
                return this.eventCodeField;
            }
            set {
                this.eventCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EventMsg {
            get {
                return this.eventMsgField;
            }
            set {
                this.eventMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class DummyResponse {
        
        private string appServerField;
        
        private string dbServerField;
        
        private string authServerField;
        
        /// <remarks/>
        public string AppServer {
            get {
                return this.appServerField;
            }
            set {
                this.appServerField = value;
            }
        }
        
        /// <remarks/>
        public string DbServer {
            get {
                return this.dbServerField;
            }
            set {
                this.dbServerField = value;
            }
        }
        
        /// <remarks/>
        public string AuthServer {
            get {
                return this.authServerField;
            }
            set {
                this.authServerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFE_LastCMP_Response {
        
        private long cbte_nroField;
        
        private string cbte_fechaField;
        
        /// <remarks/>
        public long Cbte_nro {
            get {
                return this.cbte_nroField;
            }
            set {
                this.cbte_nroField = value;
            }
        }
        
        /// <remarks/>
        public string Cbte_fecha {
            get {
                return this.cbte_fechaField;
            }
            set {
                this.cbte_fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponseLast_CMP {
        
        private ClsBFE_LastCMP_Response bFEResult_LastCMPField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFE_LastCMP_Response BFEResult_LastCMP {
            get {
                return this.bFEResult_LastCMPField;
            }
            set {
                this.bFEResult_LastCMPField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFE_LastCMP {
        
        private string tokenField;
        
        private string signField;
        
        private long cuitField;
        
        private short pto_ventaField;
        
        private short tipo_cbteField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        public long Cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
            }
        }
        
        /// <remarks/>
        public short Pto_venta {
            get {
                return this.pto_ventaField;
            }
            set {
                this.pto_ventaField = value;
            }
        }
        
        /// <remarks/>
        public short Tipo_cbte {
            get {
                return this.tipo_cbteField;
            }
            set {
                this.tipo_cbteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_Mon {
        
        private string mon_IdField;
        
        private string mon_DsField;
        
        private string mon_vig_desdeField;
        
        private string mon_vig_hastaField;
        
        /// <remarks/>
        public string Mon_Id {
            get {
                return this.mon_IdField;
            }
            set {
                this.mon_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Mon_Ds {
            get {
                return this.mon_DsField;
            }
            set {
                this.mon_DsField = value;
            }
        }
        
        /// <remarks/>
        public string Mon_vig_desde {
            get {
                return this.mon_vig_desdeField;
            }
            set {
                this.mon_vig_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string Mon_vig_hasta {
            get {
                return this.mon_vig_hastaField;
            }
            set {
                this.mon_vig_hastaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_Mon {
        
        private ClsBFEResponse_Mon[] bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_Mon[] BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_NCM {
        
        private string nCM_CodigoField;
        
        private string nCM_DsField;
        
        private string nCM_NotaField;
        
        private string nCM_vig_desdeField;
        
        private string nCM_vig_hastaField;
        
        /// <remarks/>
        public string NCM_Codigo {
            get {
                return this.nCM_CodigoField;
            }
            set {
                this.nCM_CodigoField = value;
            }
        }
        
        /// <remarks/>
        public string NCM_Ds {
            get {
                return this.nCM_DsField;
            }
            set {
                this.nCM_DsField = value;
            }
        }
        
        /// <remarks/>
        public string NCM_Nota {
            get {
                return this.nCM_NotaField;
            }
            set {
                this.nCM_NotaField = value;
            }
        }
        
        /// <remarks/>
        public string NCM_vig_desde {
            get {
                return this.nCM_vig_desdeField;
            }
            set {
                this.nCM_vig_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string NCM_vig_hasta {
            get {
                return this.nCM_vig_hastaField;
            }
            set {
                this.nCM_vig_hastaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_NCM {
        
        private ClsBFEResponse_NCM[] bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_NCM[] BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_UMed {
        
        private short umed_IdField;
        
        private string umed_DsField;
        
        private string umed_vig_desdeField;
        
        private string umed_vig_hastaField;
        
        /// <remarks/>
        public short Umed_Id {
            get {
                return this.umed_IdField;
            }
            set {
                this.umed_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Umed_Ds {
            get {
                return this.umed_DsField;
            }
            set {
                this.umed_DsField = value;
            }
        }
        
        /// <remarks/>
        public string Umed_vig_desde {
            get {
                return this.umed_vig_desdeField;
            }
            set {
                this.umed_vig_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string Umed_vig_hasta {
            get {
                return this.umed_vig_hastaField;
            }
            set {
                this.umed_vig_hastaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_Umed {
        
        private ClsBFEResponse_UMed[] bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_UMed[] BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_Tipo_Cbte {
        
        private short cbte_IdField;
        
        private string cbte_DsField;
        
        private string cbte_vig_desdeField;
        
        private string cbte_vig_hastaField;
        
        /// <remarks/>
        public short Cbte_Id {
            get {
                return this.cbte_IdField;
            }
            set {
                this.cbte_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Cbte_Ds {
            get {
                return this.cbte_DsField;
            }
            set {
                this.cbte_DsField = value;
            }
        }
        
        /// <remarks/>
        public string Cbte_vig_desde {
            get {
                return this.cbte_vig_desdeField;
            }
            set {
                this.cbte_vig_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string Cbte_vig_hasta {
            get {
                return this.cbte_vig_hastaField;
            }
            set {
                this.cbte_vig_hastaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_Tipo_Cbte {
        
        private ClsBFEResponse_Tipo_Cbte[] bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_Tipo_Cbte[] BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_Zon {
        
        private short zon_IdField;
        
        private string zon_DsField;
        
        private string zon_vig_desdeField;
        
        private string zon_vig_hastaField;
        
        /// <remarks/>
        public short Zon_Id {
            get {
                return this.zon_IdField;
            }
            set {
                this.zon_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Zon_Ds {
            get {
                return this.zon_DsField;
            }
            set {
                this.zon_DsField = value;
            }
        }
        
        /// <remarks/>
        public string Zon_vig_desde {
            get {
                return this.zon_vig_desdeField;
            }
            set {
                this.zon_vig_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string Zon_vig_hasta {
            get {
                return this.zon_vig_hastaField;
            }
            set {
                this.zon_vig_hastaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_Zon {
        
        private ClsBFEResponse_Zon[] bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_Zon[] BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_Tipo_IVA {
        
        private short iVA_IdField;
        
        private string iVA_DsField;
        
        private string iVA_vig_desdeField;
        
        private string iVA_vig_hastaField;
        
        /// <remarks/>
        public short IVA_Id {
            get {
                return this.iVA_IdField;
            }
            set {
                this.iVA_IdField = value;
            }
        }
        
        /// <remarks/>
        public string IVA_Ds {
            get {
                return this.iVA_DsField;
            }
            set {
                this.iVA_DsField = value;
            }
        }
        
        /// <remarks/>
        public string IVA_vig_desde {
            get {
                return this.iVA_vig_desdeField;
            }
            set {
                this.iVA_vig_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string IVA_vig_hasta {
            get {
                return this.iVA_vig_hastaField;
            }
            set {
                this.iVA_vig_hastaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_Tipo_IVA {
        
        private ClsBFEResponse_Tipo_IVA[] bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_Tipo_IVA[] BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEResponse_Tipo_doc {
        
        private short doc_IdField;
        
        private string doc_DsField;
        
        private string doc_vig_desdeField;
        
        private string doc_vig_hastaField;
        
        /// <remarks/>
        public short Doc_Id {
            get {
                return this.doc_IdField;
            }
            set {
                this.doc_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Doc_Ds {
            get {
                return this.doc_DsField;
            }
            set {
                this.doc_DsField = value;
            }
        }
        
        /// <remarks/>
        public string Doc_vig_desde {
            get {
                return this.doc_vig_desdeField;
            }
            set {
                this.doc_vig_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string Doc_vig_hasta {
            get {
                return this.doc_vig_hastaField;
            }
            set {
                this.doc_vig_hastaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponse_Tipo_doc {
        
        private ClsBFEResponse_Tipo_doc[] bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEResponse_Tipo_doc[] BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEGetCMPR {
        
        private long idField;
        
        private long cuitField;
        
        private short tipo_docField;
        
        private long nro_docField;
        
        private short tipo_cbteField;
        
        private int punto_vtaField;
        
        private long cbte_nroField;
        
        private double imp_totalField;
        
        private double imp_tot_concField;
        
        private double imp_netoField;
        
        private double impto_liqField;
        
        private double impto_liq_rniField;
        
        private double imp_op_exField;
        
        private double imp_percField;
        
        private double imp_iibbField;
        
        private double imp_perc_munField;
        
        private double imp_internosField;
        
        private string imp_moneda_IdField;
        
        private double imp_moneda_ctzField;
        
        private string fecha_cbte_origField;
        
        private string fecha_cbte_caeField;
        
        private string fch_venc_CaeField;
        
        private string caeField;
        
        private string resultadoField;
        
        private string obsField;
        
        private Item[] itemsField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long Cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
            }
        }
        
        /// <remarks/>
        public short Tipo_doc {
            get {
                return this.tipo_docField;
            }
            set {
                this.tipo_docField = value;
            }
        }
        
        /// <remarks/>
        public long Nro_doc {
            get {
                return this.nro_docField;
            }
            set {
                this.nro_docField = value;
            }
        }
        
        /// <remarks/>
        public short Tipo_cbte {
            get {
                return this.tipo_cbteField;
            }
            set {
                this.tipo_cbteField = value;
            }
        }
        
        /// <remarks/>
        public int Punto_vta {
            get {
                return this.punto_vtaField;
            }
            set {
                this.punto_vtaField = value;
            }
        }
        
        /// <remarks/>
        public long Cbte_nro {
            get {
                return this.cbte_nroField;
            }
            set {
                this.cbte_nroField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_total {
            get {
                return this.imp_totalField;
            }
            set {
                this.imp_totalField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_tot_conc {
            get {
                return this.imp_tot_concField;
            }
            set {
                this.imp_tot_concField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_neto {
            get {
                return this.imp_netoField;
            }
            set {
                this.imp_netoField = value;
            }
        }
        
        /// <remarks/>
        public double Impto_liq {
            get {
                return this.impto_liqField;
            }
            set {
                this.impto_liqField = value;
            }
        }
        
        /// <remarks/>
        public double Impto_liq_rni {
            get {
                return this.impto_liq_rniField;
            }
            set {
                this.impto_liq_rniField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_op_ex {
            get {
                return this.imp_op_exField;
            }
            set {
                this.imp_op_exField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_perc {
            get {
                return this.imp_percField;
            }
            set {
                this.imp_percField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_iibb {
            get {
                return this.imp_iibbField;
            }
            set {
                this.imp_iibbField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_perc_mun {
            get {
                return this.imp_perc_munField;
            }
            set {
                this.imp_perc_munField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_internos {
            get {
                return this.imp_internosField;
            }
            set {
                this.imp_internosField = value;
            }
        }
        
        /// <remarks/>
        public string Imp_moneda_Id {
            get {
                return this.imp_moneda_IdField;
            }
            set {
                this.imp_moneda_IdField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_moneda_ctz {
            get {
                return this.imp_moneda_ctzField;
            }
            set {
                this.imp_moneda_ctzField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha_cbte_orig {
            get {
                return this.fecha_cbte_origField;
            }
            set {
                this.fecha_cbte_origField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha_cbte_cae {
            get {
                return this.fecha_cbte_caeField;
            }
            set {
                this.fecha_cbte_caeField = value;
            }
        }
        
        /// <remarks/>
        public string Fch_venc_Cae {
            get {
                return this.fch_venc_CaeField;
            }
            set {
                this.fch_venc_CaeField = value;
            }
        }
        
        /// <remarks/>
        public string Cae {
            get {
                return this.caeField;
            }
            set {
                this.caeField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string Obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
            }
        }
        
        /// <remarks/>
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class Item {
        
        private string pro_codigo_ncmField;
        
        private string pro_codigo_secField;
        
        private string pro_dsField;
        
        private double pro_qtyField;
        
        private int pro_umedField;
        
        private double pro_precio_uniField;
        
        private double imp_bonifField;
        
        private double imp_totalField;
        
        private short iva_idField;
        
        /// <remarks/>
        public string Pro_codigo_ncm {
            get {
                return this.pro_codigo_ncmField;
            }
            set {
                this.pro_codigo_ncmField = value;
            }
        }
        
        /// <remarks/>
        public string Pro_codigo_sec {
            get {
                return this.pro_codigo_secField;
            }
            set {
                this.pro_codigo_secField = value;
            }
        }
        
        /// <remarks/>
        public string Pro_ds {
            get {
                return this.pro_dsField;
            }
            set {
                this.pro_dsField = value;
            }
        }
        
        /// <remarks/>
        public double Pro_qty {
            get {
                return this.pro_qtyField;
            }
            set {
                this.pro_qtyField = value;
            }
        }
        
        /// <remarks/>
        public int Pro_umed {
            get {
                return this.pro_umedField;
            }
            set {
                this.pro_umedField = value;
            }
        }
        
        /// <remarks/>
        public double Pro_precio_uni {
            get {
                return this.pro_precio_uniField;
            }
            set {
                this.pro_precio_uniField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_bonif {
            get {
                return this.imp_bonifField;
            }
            set {
                this.imp_bonifField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_total {
            get {
                return this.imp_totalField;
            }
            set {
                this.imp_totalField = value;
            }
        }
        
        /// <remarks/>
        public short Iva_id {
            get {
                return this.iva_idField;
            }
            set {
                this.iva_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEGetCMPResponse {
        
        private ClsBFEGetCMPR bFEResultGetField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEGetCMPR BFEResultGet {
            get {
                return this.bFEResultGetField;
            }
            set {
                this.bFEResultGetField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEGetCMP {
        
        private short tipo_cbteField;
        
        private int punto_vtaField;
        
        private long cbte_nroField;
        
        /// <remarks/>
        public short Tipo_cbte {
            get {
                return this.tipo_cbteField;
            }
            set {
                this.tipo_cbteField = value;
            }
        }
        
        /// <remarks/>
        public int Punto_vta {
            get {
                return this.punto_vtaField;
            }
            set {
                this.punto_vtaField = value;
            }
        }
        
        /// <remarks/>
        public long Cbte_nro {
            get {
                return this.cbte_nroField;
            }
            set {
                this.cbte_nroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFEOutAuthorize {
        
        private long idField;
        
        private long cuitField;
        
        private string caeField;
        
        private string fch_venc_CaeField;
        
        private string fch_cbteField;
        
        private string resultadoField;
        
        private string reprocesoField;
        
        private string obsField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long Cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
            }
        }
        
        /// <remarks/>
        public string Cae {
            get {
                return this.caeField;
            }
            set {
                this.caeField = value;
            }
        }
        
        /// <remarks/>
        public string Fch_venc_Cae {
            get {
                return this.fch_venc_CaeField;
            }
            set {
                this.fch_venc_CaeField = value;
            }
        }
        
        /// <remarks/>
        public string Fch_cbte {
            get {
                return this.fch_cbteField;
            }
            set {
                this.fch_cbteField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string Reproceso {
            get {
                return this.reprocesoField;
            }
            set {
                this.reprocesoField = value;
            }
        }
        
        /// <remarks/>
        public string Obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class BFEResponseAuthorize {
        
        private ClsBFEOutAuthorize bFEResultAuthField;
        
        private ClsBFEErr bFEErrField;
        
        private ClsBFEEvents bFEEventsField;
        
        /// <remarks/>
        public ClsBFEOutAuthorize BFEResultAuth {
            get {
                return this.bFEResultAuthField;
            }
            set {
                this.bFEResultAuthField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEErr BFEErr {
            get {
                return this.bFEErrField;
            }
            set {
                this.bFEErrField = value;
            }
        }
        
        /// <remarks/>
        public ClsBFEEvents BFEEvents {
            get {
                return this.bFEEventsField;
            }
            set {
                this.bFEEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.bfe/")]
    public partial class ClsBFERequest {
        
        private long idField;
        
        private short tipo_docField;
        
        private long nro_docField;
        
        private short zonaField;
        
        private short tipo_cbteField;
        
        private int punto_vtaField;
        
        private long cbte_nroField;
        
        private double imp_totalField;
        
        private double imp_tot_concField;
        
        private double imp_netoField;
        
        private double impto_liqField;
        
        private double impto_liq_rniField;
        
        private double imp_op_exField;
        
        private double imp_percField;
        
        private double imp_iibbField;
        
        private double imp_perc_munField;
        
        private double imp_internosField;
        
        private string imp_moneda_IdField;
        
        private double imp_moneda_ctzField;
        
        private string fecha_cbteField;
        
        private Item[] itemsField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public short Tipo_doc {
            get {
                return this.tipo_docField;
            }
            set {
                this.tipo_docField = value;
            }
        }
        
        /// <remarks/>
        public long Nro_doc {
            get {
                return this.nro_docField;
            }
            set {
                this.nro_docField = value;
            }
        }
        
        /// <remarks/>
        public short Zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
            }
        }
        
        /// <remarks/>
        public short Tipo_cbte {
            get {
                return this.tipo_cbteField;
            }
            set {
                this.tipo_cbteField = value;
            }
        }
        
        /// <remarks/>
        public int Punto_vta {
            get {
                return this.punto_vtaField;
            }
            set {
                this.punto_vtaField = value;
            }
        }
        
        /// <remarks/>
        public long Cbte_nro {
            get {
                return this.cbte_nroField;
            }
            set {
                this.cbte_nroField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_total {
            get {
                return this.imp_totalField;
            }
            set {
                this.imp_totalField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_tot_conc {
            get {
                return this.imp_tot_concField;
            }
            set {
                this.imp_tot_concField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_neto {
            get {
                return this.imp_netoField;
            }
            set {
                this.imp_netoField = value;
            }
        }
        
        /// <remarks/>
        public double Impto_liq {
            get {
                return this.impto_liqField;
            }
            set {
                this.impto_liqField = value;
            }
        }
        
        /// <remarks/>
        public double Impto_liq_rni {
            get {
                return this.impto_liq_rniField;
            }
            set {
                this.impto_liq_rniField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_op_ex {
            get {
                return this.imp_op_exField;
            }
            set {
                this.imp_op_exField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_perc {
            get {
                return this.imp_percField;
            }
            set {
                this.imp_percField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_iibb {
            get {
                return this.imp_iibbField;
            }
            set {
                this.imp_iibbField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_perc_mun {
            get {
                return this.imp_perc_munField;
            }
            set {
                this.imp_perc_munField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_internos {
            get {
                return this.imp_internosField;
            }
            set {
                this.imp_internosField = value;
            }
        }
        
        /// <remarks/>
        public string Imp_moneda_Id {
            get {
                return this.imp_moneda_IdField;
            }
            set {
                this.imp_moneda_IdField = value;
            }
        }
        
        /// <remarks/>
        public double Imp_moneda_ctz {
            get {
                return this.imp_moneda_ctzField;
            }
            set {
                this.imp_moneda_ctzField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha_cbte {
            get {
                return this.fecha_cbteField;
            }
            set {
                this.fecha_cbteField = value;
            }
        }
        
        /// <remarks/>
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEAuthorizeCompletedEventHandler(object sender, BFEAuthorizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEAuthorizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEAuthorizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponseAuthorize Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponseAuthorize)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetCMPCompletedEventHandler(object sender, BFEGetCMPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetCMPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetCMPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEGetCMPResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEGetCMPResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetPARAM_Tipo_docCompletedEventHandler(object sender, BFEGetPARAM_Tipo_docCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetPARAM_Tipo_docCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetPARAM_Tipo_docCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_Tipo_doc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_Tipo_doc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetPARAM_Tipo_IVACompletedEventHandler(object sender, BFEGetPARAM_Tipo_IVACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetPARAM_Tipo_IVACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetPARAM_Tipo_IVACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_Tipo_IVA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_Tipo_IVA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetPARAM_ZonasCompletedEventHandler(object sender, BFEGetPARAM_ZonasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetPARAM_ZonasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetPARAM_ZonasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_Zon Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_Zon)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetPARAM_Tipo_CbteCompletedEventHandler(object sender, BFEGetPARAM_Tipo_CbteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetPARAM_Tipo_CbteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetPARAM_Tipo_CbteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_Tipo_Cbte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_Tipo_Cbte)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetPARAM_UMedCompletedEventHandler(object sender, BFEGetPARAM_UMedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetPARAM_UMedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetPARAM_UMedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_Umed Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_Umed)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetPARAM_NCMCompletedEventHandler(object sender, BFEGetPARAM_NCMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetPARAM_NCMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetPARAM_NCMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_NCM Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_NCM)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetPARAM_MONCompletedEventHandler(object sender, BFEGetPARAM_MONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetPARAM_MONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetPARAM_MONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_Mon Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_Mon)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetLast_CMPCompletedEventHandler(object sender, BFEGetLast_CMPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetLast_CMPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetLast_CMPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponseLast_CMP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponseLast_CMP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEDummyCompletedEventHandler(object sender, BFEDummyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEDummyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEDummyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DummyResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DummyResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BFEGetLast_IDCompletedEventHandler(object sender, BFEGetLast_IDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BFEGetLast_IDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BFEGetLast_IDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BFEResponse_LastID Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BFEResponse_LastID)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591